### ISSUE TITLE
Files not needed for version control

### ISSUE THREAD

**Issue by ucyo** [Julian3012/ClimaData_BokehReact#2]
Hi @Julian3012,
I think there are several files in the repository which are not needed to be tracked by git e.g.
```
.vscode/
node_modules/
.DS_Store
package-lock.json
```
Can you test if you can remove these files?

**Comment by ucyo** [comment]
The following could be used
```git rm -r --cached .```

**Comment by Julian3012** [comment]
Files removed and updated gitignore
