### ISSUE TITLE
Readme instructions wrong

### ISSUE THREAD

**Issue by ucyo** [Julian3012/ClimaData_BokehReact#3]
Hi @Julian3012,

when executing `conda create env -f env_files/environment_newVersions.yml` after cloning I get the following error message:

```
CondaValueError: The target prefix is the base prefix. Aborting.
``` 
What is wrong?

**Comment by ucyo** [comment]
Additionally ... Line 173 is only a logger statement and 176 an if clause. 
Wrong lines in the documentation?
 https://github.com/Julian3012/ClimaData_BokehReact/blob/d1004e1da998d5fd9340e061cfa58c1d7633e8f4/main_backend.py#L173-L176

**Comment by Julian3012** [comment]
README ist updated. Referring to the bokeh versions, I decided to use the old versions for now.
